### PR TITLE
use zone.js to add context to share data between interceptors

### PR DESCRIPTION
**Pull request by JiaLiPassion**
Based on #50, add a context to share data between interceptors, to keep the current interface unchange, use a interceptorZone to share data.

to set data in context.

```javascript
    let interceptor = (data, method) => { 
        let context = getContext();
        if (context) context['key'] = 'value';
        return data;
    }

    let otherInterceptor = (data, method) => { 
        let context = getContext();
        if (context) let sharedData = context['key'];
        return data;
    }
```

### CODE REVIEW

**Comment by gund** [comment]
Thanks for making PR.

Everything looks cool but one thing I'm concerned about is wouldn't [Zone.fork()](https://github.com/gund/ng2-http-interceptor/pull/51/files#diff-6b43039ad61fd67e61d1e2e23500949dR35) be a performance bottleneck to do it for every HTTP request? (maybe it's better to create and share zone between requests?).
I did not make any benchmarks so I might be wrong about it.

What do you think?

**Comment by JiaLiPassion** [comment]
Yes, I understand your concern.
I think the zone will not become a bottleneck because:

- All angular2 are already in zone, so Zone.fork will just create new a Zone object add add a zone frame.
- this zonespec is simple, only have a properties object, and will not intercept any async function invocation(such as scheduleTask or InvokeTask)
- I tried in some other projects, that except longstacktrace zone, the zone like this will not impact performance cause it is really just a function wrapper.

>  (maybe it's better to create and share zone between requests?).

To make every request have it's own shared area, we have to create a isolate zone for each apply call. So multiple requests will not conflict with each other.

please review, thank you.

**Comment by gund** [comment]
I've been thinking this time wouldn't this solution be too complicated for such easy thing.
For example it's not clear where function `getContext()` comes from.
And also why would we need to fork a zone every time if we really can just use empty object for context within third argument in `Interceptor` interface function.
It won't break existing API but extend it, and is easy to use.

What are your thoughts about it? Is there any other benefits of using Zone against plain old JS Object?

**Comment by JiaLiPassion** [comment]
Yes, I agree with you. The reason I use zone instead of a context object is  just I don't want to change the current API. Maybe just add an optional argument is much more easier to understand.
just like this,

```javascript
export interface Interceptor<T, D> {
  (data: T, method: string, context? any): D;
}
```

**Comment by gund** [comment]
Sure this looks a lot much easier and less error prone.
I appreciate the time you dedicated for implementing this solution and sorry for not using it =)
Would you like to update it in this PR as we discussed or should I close it?

**Comment by JiaLiPassion** [comment]
Sure, I will update my PR with this new solution. Thank you:)

**Comment by gund** [comment]
Thank you. Will wait for it =)

**Comment by gund** [comment]
Hi @JiaLiPassion, have you had a time to look into this? Thanks

**Comment by JiaLiPassion** [comment]
@gund, sorry for the delay, I will  finish it in this weekend.

**Pull request closed without merging**
